[[annotation]]
file = "/home/zmvanw01/ref/beds/gene.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Gene"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/intron.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Introns"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/exon_1.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Exon1"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/exon_2.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Exon2"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/l-part2.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["LPart2"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/heptamer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Heptamer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/nonamer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Nonamer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/spacer.bed.gz"
columns = [4]  # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Spacer"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/region.bed.gz"
columns = [4] # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["Region"]  # Name(s) for the annotation in the output

[[annotation]]
file = "/home/zmvanw01/ref/beds/utr.bed.gz"
columns = [4] # Column(s) in the BED file to use as annotation
ops = ["self"]  # Use the raw values from the BED file
names = ["UTR"]  # Name(s) for the annotation in the output
